/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as BiRouteImport } from './routes/bi'
import { Route as ConversasWhatsappRouteImport } from './routes/conversas-whatsapp'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as IaComercialRouteImport } from './routes/ia-comercial'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetaAdsRouteImport } from './routes/meta-ads'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ApiGrowthRouteImport } from './routes/api/growth'
import { Route as ApiIaComercialRouteImport } from './routes/api/ia-comercial'
import { Route as ApiMetaAdsRouteImport } from './routes/api/meta-ads'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiSystemFeedbackRouteImport } from './routes/api/system-feedback'
import { Route as ApiSystemSettingsRouteImport } from './routes/api/system-settings'
import { Route as ApiTrainingRouteImport } from './routes/api/training'
import { Route as ApiWhatsappSupervisionRouteImport } from './routes/api/whatsapp-supervision'
import { Route as CrmImportarRouteImport } from './routes/crm.importar'
import { Route as CrmTransferenciaRouteImport } from './routes/crm.transferencia'
import { Route as GestaoCadastroRouteImport } from './routes/gestao.cadastro'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as ApiAdminUnitsRouteImport } from './routes/api/admin/units'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAtendimentosMidiaRouteImport } from './routes/api/atendimentos.midia'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiCrmImportRouteImport } from './routes/api/crm/import'
import { Route as ApiCrmLeadsRouteImport } from './routes/api/crm/leads'
import { Route as ApiCrmTasksRouteImport } from './routes/api/crm/tasks'
import { Route as ApiCrmTransferRouteImport } from './routes/api/crm/transfer'
import { Route as ApiCronWhatsappAnalysisRouteImport } from './routes/api/cron.whatsapp-analysis'
import { Route as ApiGestaoAttendancesRouteImport } from './routes/api/gestao/attendances'
import { Route as ApiGestaoChannelsRouteImport } from './routes/api/gestao/channels'
import { Route as ApiGestaoCoursesRouteImport } from './routes/api/gestao/courses'
import { Route as ApiGestaoPipelineColumnsRouteImport } from './routes/api/gestao/pipeline-columns'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiIaComercialAnalisesRouteImport } from './routes/api/ia-comercial.analises'
import { Route as ApiIaComercialScriptsRouteImport } from './routes/api/ia-comercial.scripts'
import { Route as ApiIntegrationsEvolutionRouteImport } from './routes/api/integrations/evolution'
import { Route as ApiMetaConnectUrlRouteImport } from './routes/api/meta/connect-url'
import { Route as ApiMetaOauthCompleteRouteImport } from './routes/api/meta/oauth-complete'
import { Route as ApiTrainingVideoRouteImport } from './routes/api/training.video'
import { Route as ApiWebhooksEvolutionRouteImport } from './routes/api/webhooks/evolution'
import { Route as ApiWebhooksMetaLeadsRouteImport } from './routes/api/webhooks/meta-leads'
import { Route as ApiWhatsappSupervisionAccessRouteImport } from './routes/api/whatsapp-supervision.access'
import { Route as ApiWhatsappSupervisionNotificationsRouteImport } from './routes/api/whatsapp-supervision.notifications'
import { Route as FinanceiroAlunoStudentIdRouteImport } from './routes/financeiro.aluno.$studentId'
import { Route as ApiCrmLeadsIdRouteImport } from './routes/api/crm/leads.$id'
import { Route as ApiGestaoChannelsIdRouteImport } from './routes/api/gestao/channels.$id'
import { Route as ApiGestaoCoursesIdRouteImport } from './routes/api/gestao/courses.$id'
import { Route as ApiWhatsappSupervisionConversationsIdRouteImport } from './routes/api/whatsapp-supervision.conversations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasWhatsappRoute = ConversasWhatsappRouteImport.update({
  id: '/conversas-whatsapp',
  path: '/conversas-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const IaComercialRoute = IaComercialRouteImport.update({
  id: '/ia-comercial',
  path: '/ia-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaAdsRoute = MetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrowthRoute = ApiGrowthRouteImport.update({
  id: '/api/growth',
  path: '/api/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaComercialRoute = ApiIaComercialRouteImport.update({
  id: '/api/ia-comercial',
  path: '/api/ia-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaAdsRoute = ApiMetaAdsRouteImport.update({
  id: '/api/meta-ads',
  path: '/api/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemFeedbackRoute = ApiSystemFeedbackRouteImport.update({
  id: '/api/system-feedback',
  path: '/api/system-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemSettingsRoute = ApiSystemSettingsRouteImport.update({
  id: '/api/system-settings',
  path: '/api/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainingRoute = ApiTrainingRouteImport.update({
  id: '/api/training',
  path: '/api/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSupervisionRoute = ApiWhatsappSupervisionRouteImport.update({
  id: '/api/whatsapp-supervision',
  path: '/api/whatsapp-supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmImportarRoute = CrmImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTransferenciaRoute = CrmTransferenciaRouteImport.update({
  id: '/transferencia',
  path: '/transferencia',
  getParentRoute: () => CrmRoute,
} as any)
const GestaoCadastroRoute = GestaoCadastroRouteImport.update({
  id: '/gestao/cadastro',
  path: '/gestao/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUnitsRoute = ApiAdminUnitsRouteImport.update({
  id: '/api/admin/units',
  path: '/api/admin/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtendimentosMidiaRoute = ApiAtendimentosMidiaRouteImport.update({
  id: '/api/atendimentos/midia',
  path: '/api/atendimentos/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmImportRoute = ApiCrmImportRouteImport.update({
  id: '/api/crm/import',
  path: '/api/crm/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmLeadsRoute = ApiCrmLeadsRouteImport.update({
  id: '/api/crm/leads',
  path: '/api/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTasksRoute = ApiCrmTasksRouteImport.update({
  id: '/api/crm/tasks',
  path: '/api/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTransferRoute = ApiCrmTransferRouteImport.update({
  id: '/api/crm/transfer',
  path: '/api/crm/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWhatsappAnalysisRoute = ApiCronWhatsappAnalysisRouteImport.update({
  id: '/api/cron/whatsapp-analysis',
  path: '/api/cron/whatsapp-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoAttendancesRoute = ApiGestaoAttendancesRouteImport.update({
  id: '/api/gestao/attendances',
  path: '/api/gestao/attendances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoChannelsRoute = ApiGestaoChannelsRouteImport.update({
  id: '/api/gestao/channels',
  path: '/api/gestao/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCoursesRoute = ApiGestaoCoursesRouteImport.update({
  id: '/api/gestao/courses',
  path: '/api/gestao/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoPipelineColumnsRoute =
  ApiGestaoPipelineColumnsRouteImport.update({
    id: '/api/gestao/pipeline-columns',
    path: '/api/gestao/pipeline-columns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIaComercialAnalisesRoute = ApiIaComercialAnalisesRouteImport.update({
  id: '/analises',
  path: '/analises',
  getParentRoute: () => ApiIaComercialRoute,
} as any)
const ApiIaComercialScriptsRoute = ApiIaComercialScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => ApiIaComercialRoute,
} as any)
const ApiIntegrationsEvolutionRoute =
  ApiIntegrationsEvolutionRouteImport.update({
    id: '/api/integrations/evolution',
    path: '/api/integrations/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaConnectUrlRoute = ApiMetaConnectUrlRouteImport.update({
  id: '/api/meta/connect-url',
  path: '/api/meta/connect-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaOauthCompleteRoute = ApiMetaOauthCompleteRouteImport.update({
  id: '/api/meta/oauth-complete',
  path: '/api/meta/oauth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainingVideoRoute = ApiTrainingVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ApiTrainingRoute,
} as any)
const ApiWebhooksEvolutionRoute = ApiWebhooksEvolutionRouteImport.update({
  id: '/api/webhooks/evolution',
  path: '/api/webhooks/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaLeadsRoute = ApiWebhooksMetaLeadsRouteImport.update({
  id: '/api/webhooks/meta-leads',
  path: '/api/webhooks/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSupervisionAccessRoute =
  ApiWhatsappSupervisionAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => ApiWhatsappSupervisionRoute,
  } as any)
const ApiWhatsappSupervisionNotificationsRoute =
  ApiWhatsappSupervisionNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ApiWhatsappSupervisionRoute,
  } as any)
const FinanceiroAlunoStudentIdRoute =
  FinanceiroAlunoStudentIdRouteImport.update({
    id: '/aluno/$studentId',
    path: '/aluno/$studentId',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const ApiCrmLeadsIdRoute = ApiCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCrmLeadsRoute,
} as any)
const ApiGestaoChannelsIdRoute = ApiGestaoChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoChannelsRoute,
} as any)
const ApiGestaoCoursesIdRoute = ApiGestaoCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoCoursesRoute,
} as any)
const ApiWhatsappSupervisionConversationsIdRoute =
  ApiWhatsappSupervisionConversationsIdRouteImport.update({
    id: '/conversations/$id',
    path: '/conversations/$id',
    getParentRoute: () => ApiWhatsappSupervisionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/bi': typeof BiRoute
  '/conversas-whatsapp': typeof ConversasWhatsappRoute
  '/crm': typeof CrmRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/ia-comercial': typeof IaComercialRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/treinamentos': typeof TreinamentosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/ia-comercial': typeof ApiIaComercialRouteWithChildren
  '/api/meta-ads': typeof ApiMetaAdsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/api/whatsapp-supervision': typeof ApiWhatsappSupervisionRouteWithChildren
  '/crm/importar': typeof CrmImportarRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/atendimentos/midia': typeof ApiAtendimentosMidiaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/import': typeof ApiCrmImportRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/cron/whatsapp-analysis': typeof ApiCronWhatsappAnalysisRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/gestao/pipeline-columns': typeof ApiGestaoPipelineColumnsRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/ia-comercial/analises': typeof ApiIaComercialAnalisesRoute
  '/api/ia-comercial/scripts': typeof ApiIaComercialScriptsRoute
  '/api/integrations/evolution': typeof ApiIntegrationsEvolutionRoute
  '/api/meta/connect-url': typeof ApiMetaConnectUrlRoute
  '/api/meta/oauth-complete': typeof ApiMetaOauthCompleteRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/whatsapp-supervision/access': typeof ApiWhatsappSupervisionAccessRoute
  '/api/whatsapp-supervision/notifications': typeof ApiWhatsappSupervisionNotificationsRoute
  '/financeiro/aluno/$studentId': typeof FinanceiroAlunoStudentIdRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
  '/api/whatsapp-supervision/conversations/$id': typeof ApiWhatsappSupervisionConversationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/bi': typeof BiRoute
  '/conversas-whatsapp': typeof ConversasWhatsappRoute
  '/crm': typeof CrmRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/ia-comercial': typeof IaComercialRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/treinamentos': typeof TreinamentosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/ia-comercial': typeof ApiIaComercialRouteWithChildren
  '/api/meta-ads': typeof ApiMetaAdsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/api/whatsapp-supervision': typeof ApiWhatsappSupervisionRouteWithChildren
  '/crm/importar': typeof CrmImportarRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/atendimentos/midia': typeof ApiAtendimentosMidiaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/import': typeof ApiCrmImportRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/cron/whatsapp-analysis': typeof ApiCronWhatsappAnalysisRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/gestao/pipeline-columns': typeof ApiGestaoPipelineColumnsRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/ia-comercial/analises': typeof ApiIaComercialAnalisesRoute
  '/api/ia-comercial/scripts': typeof ApiIaComercialScriptsRoute
  '/api/integrations/evolution': typeof ApiIntegrationsEvolutionRoute
  '/api/meta/connect-url': typeof ApiMetaConnectUrlRoute
  '/api/meta/oauth-complete': typeof ApiMetaOauthCompleteRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/whatsapp-supervision/access': typeof ApiWhatsappSupervisionAccessRoute
  '/api/whatsapp-supervision/notifications': typeof ApiWhatsappSupervisionNotificationsRoute
  '/financeiro/aluno/$studentId': typeof FinanceiroAlunoStudentIdRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
  '/api/whatsapp-supervision/conversations/$id': typeof ApiWhatsappSupervisionConversationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/bi': typeof BiRoute
  '/conversas-whatsapp': typeof ConversasWhatsappRoute
  '/crm': typeof CrmRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/ia-comercial': typeof IaComercialRoute
  '/login': typeof LoginRoute
  '/meta-ads': typeof MetaAdsRoute
  '/perfil': typeof PerfilRoute
  '/treinamentos': typeof TreinamentosRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/growth': typeof ApiGrowthRoute
  '/api/ia-comercial': typeof ApiIaComercialRouteWithChildren
  '/api/meta-ads': typeof ApiMetaAdsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-feedback': typeof ApiSystemFeedbackRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/api/training': typeof ApiTrainingRouteWithChildren
  '/api/whatsapp-supervision': typeof ApiWhatsappSupervisionRouteWithChildren
  '/crm/importar': typeof CrmImportarRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/atendimentos/midia': typeof ApiAtendimentosMidiaRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/import': typeof ApiCrmImportRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/cron/whatsapp-analysis': typeof ApiCronWhatsappAnalysisRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/gestao/pipeline-columns': typeof ApiGestaoPipelineColumnsRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/ia-comercial/analises': typeof ApiIaComercialAnalisesRoute
  '/api/ia-comercial/scripts': typeof ApiIaComercialScriptsRoute
  '/api/integrations/evolution': typeof ApiIntegrationsEvolutionRoute
  '/api/meta/connect-url': typeof ApiMetaConnectUrlRoute
  '/api/meta/oauth-complete': typeof ApiMetaOauthCompleteRoute
  '/api/training/video': typeof ApiTrainingVideoRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta-leads': typeof ApiWebhooksMetaLeadsRoute
  '/api/whatsapp-supervision/access': typeof ApiWhatsappSupervisionAccessRoute
  '/api/whatsapp-supervision/notifications': typeof ApiWhatsappSupervisionNotificationsRoute
  '/financeiro/aluno/$studentId': typeof FinanceiroAlunoStudentIdRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
  '/api/whatsapp-supervision/conversations/$id': typeof ApiWhatsappSupervisionConversationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aluno'
    | '/bi'
    | '/conversas-whatsapp'
    | '/crm'
    | '/feedback'
    | '/financeiro'
    | '/ia-comercial'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/treinamentos'
    | '/unidades'
    | '/usuarios'
    | '/api/growth'
    | '/api/ia-comercial'
    | '/api/meta-ads'
    | '/api/profile'
    | '/api/system-feedback'
    | '/api/system-settings'
    | '/api/training'
    | '/api/whatsapp-supervision'
    | '/crm/importar'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/atendimentos/midia'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/import'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/cron/whatsapp-analysis'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/gestao/pipeline-columns'
    | '/api/health/db'
    | '/api/ia-comercial/analises'
    | '/api/ia-comercial/scripts'
    | '/api/integrations/evolution'
    | '/api/meta/connect-url'
    | '/api/meta/oauth-complete'
    | '/api/training/video'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta-leads'
    | '/api/whatsapp-supervision/access'
    | '/api/whatsapp-supervision/notifications'
    | '/financeiro/aluno/$studentId'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
    | '/api/whatsapp-supervision/conversations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno'
    | '/bi'
    | '/conversas-whatsapp'
    | '/crm'
    | '/feedback'
    | '/financeiro'
    | '/ia-comercial'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/treinamentos'
    | '/unidades'
    | '/usuarios'
    | '/api/growth'
    | '/api/ia-comercial'
    | '/api/meta-ads'
    | '/api/profile'
    | '/api/system-feedback'
    | '/api/system-settings'
    | '/api/training'
    | '/api/whatsapp-supervision'
    | '/crm/importar'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/atendimentos/midia'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/import'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/cron/whatsapp-analysis'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/gestao/pipeline-columns'
    | '/api/health/db'
    | '/api/ia-comercial/analises'
    | '/api/ia-comercial/scripts'
    | '/api/integrations/evolution'
    | '/api/meta/connect-url'
    | '/api/meta/oauth-complete'
    | '/api/training/video'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta-leads'
    | '/api/whatsapp-supervision/access'
    | '/api/whatsapp-supervision/notifications'
    | '/financeiro/aluno/$studentId'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
    | '/api/whatsapp-supervision/conversations/$id'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/bi'
    | '/conversas-whatsapp'
    | '/crm'
    | '/feedback'
    | '/financeiro'
    | '/ia-comercial'
    | '/login'
    | '/meta-ads'
    | '/perfil'
    | '/treinamentos'
    | '/unidades'
    | '/usuarios'
    | '/api/growth'
    | '/api/ia-comercial'
    | '/api/meta-ads'
    | '/api/profile'
    | '/api/system-feedback'
    | '/api/system-settings'
    | '/api/training'
    | '/api/whatsapp-supervision'
    | '/crm/importar'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/atendimentos/midia'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/import'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/cron/whatsapp-analysis'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/gestao/pipeline-columns'
    | '/api/health/db'
    | '/api/ia-comercial/analises'
    | '/api/ia-comercial/scripts'
    | '/api/integrations/evolution'
    | '/api/meta/connect-url'
    | '/api/meta/oauth-complete'
    | '/api/training/video'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta-leads'
    | '/api/whatsapp-supervision/access'
    | '/api/whatsapp-supervision/notifications'
    | '/financeiro/aluno/$studentId'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
    | '/api/whatsapp-supervision/conversations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRoute
  BiRoute: typeof BiRoute
  ConversasWhatsappRoute: typeof ConversasWhatsappRoute
  CrmRoute: typeof CrmRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  IaComercialRoute: typeof IaComercialRoute
  LoginRoute: typeof LoginRoute
  MetaAdsRoute: typeof MetaAdsRoute
  PerfilRoute: typeof PerfilRoute
  TreinamentosRoute: typeof TreinamentosRoute
  UnidadesRoute: typeof UnidadesRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiGrowthRoute: typeof ApiGrowthRoute
  ApiIaComercialRoute: typeof ApiIaComercialRouteWithChildren
  ApiMetaAdsRoute: typeof ApiMetaAdsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSystemFeedbackRoute: typeof ApiSystemFeedbackRoute
  ApiSystemSettingsRoute: typeof ApiSystemSettingsRoute
  ApiTrainingRoute: typeof ApiTrainingRouteWithChildren
  ApiWhatsappSupervisionRoute: typeof ApiWhatsappSupervisionRouteWithChildren
  GestaoCadastroRoute: typeof GestaoCadastroRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ApiAdminUnitsRoute: typeof ApiAdminUnitsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAtendimentosMidiaRoute: typeof ApiAtendimentosMidiaRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiCrmImportRoute: typeof ApiCrmImportRoute
  ApiCrmLeadsRoute: typeof ApiCrmLeadsRouteWithChildren
  ApiCrmTasksRoute: typeof ApiCrmTasksRoute
  ApiCrmTransferRoute: typeof ApiCrmTransferRoute
  ApiCronWhatsappAnalysisRoute: typeof ApiCronWhatsappAnalysisRoute
  ApiGestaoAttendancesRoute: typeof ApiGestaoAttendancesRoute
  ApiGestaoChannelsRoute: typeof ApiGestaoChannelsRouteWithChildren
  ApiGestaoCoursesRoute: typeof ApiGestaoCoursesRouteWithChildren
  ApiGestaoPipelineColumnsRoute: typeof ApiGestaoPipelineColumnsRoute
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  ApiIntegrationsEvolutionRoute: typeof ApiIntegrationsEvolutionRoute
  ApiMetaConnectUrlRoute: typeof ApiMetaConnectUrlRoute
  ApiMetaOauthCompleteRoute: typeof ApiMetaOauthCompleteRoute
  ApiWebhooksEvolutionRoute: typeof ApiWebhooksEvolutionRoute
  ApiWebhooksMetaLeadsRoute: typeof ApiWebhooksMetaLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas-whatsapp': {
      id: '/conversas-whatsapp'
      path: '/conversas-whatsapp'
      fullPath: '/conversas-whatsapp'
      preLoaderRoute: typeof ConversasWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-comercial': {
      id: '/ia-comercial'
      path: '/ia-comercial'
      fullPath: '/ia-comercial'
      preLoaderRoute: typeof IaComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-ads': {
      id: '/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof MetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/growth': {
      id: '/api/growth'
      path: '/api/growth'
      fullPath: '/api/growth'
      preLoaderRoute: typeof ApiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia-comercial': {
      id: '/api/ia-comercial'
      path: '/api/ia-comercial'
      fullPath: '/api/ia-comercial'
      preLoaderRoute: typeof ApiIaComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-ads': {
      id: '/api/meta-ads'
      path: '/api/meta-ads'
      fullPath: '/api/meta-ads'
      preLoaderRoute: typeof ApiMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system-feedback': {
      id: '/api/system-feedback'
      path: '/api/system-feedback'
      fullPath: '/api/system-feedback'
      preLoaderRoute: typeof ApiSystemFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system-settings': {
      id: '/api/system-settings'
      path: '/api/system-settings'
      fullPath: '/api/system-settings'
      preLoaderRoute: typeof ApiSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/training': {
      id: '/api/training'
      path: '/api/training'
      fullPath: '/api/training'
      preLoaderRoute: typeof ApiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-supervision': {
      id: '/api/whatsapp-supervision'
      path: '/api/whatsapp-supervision'
      fullPath: '/api/whatsapp-supervision'
      preLoaderRoute: typeof ApiWhatsappSupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/importar': {
      id: '/crm/importar'
      path: '/importar'
      fullPath: '/crm/importar'
      preLoaderRoute: typeof CrmImportarRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/transferencia': {
      id: '/crm/transferencia'
      path: '/transferencia'
      fullPath: '/crm/transferencia'
      preLoaderRoute: typeof CrmTransferenciaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/gestao/cadastro': {
      id: '/gestao/cadastro'
      path: '/gestao/cadastro'
      fullPath: '/gestao/cadastro'
      preLoaderRoute: typeof GestaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/units': {
      id: '/api/admin/units'
      path: '/api/admin/units'
      fullPath: '/api/admin/units'
      preLoaderRoute: typeof ApiAdminUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atendimentos/midia': {
      id: '/api/atendimentos/midia'
      path: '/api/atendimentos/midia'
      fullPath: '/api/atendimentos/midia'
      preLoaderRoute: typeof ApiAtendimentosMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/import': {
      id: '/api/crm/import'
      path: '/api/crm/import'
      fullPath: '/api/crm/import'
      preLoaderRoute: typeof ApiCrmImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/leads': {
      id: '/api/crm/leads'
      path: '/api/crm/leads'
      fullPath: '/api/crm/leads'
      preLoaderRoute: typeof ApiCrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/tasks': {
      id: '/api/crm/tasks'
      path: '/api/crm/tasks'
      fullPath: '/api/crm/tasks'
      preLoaderRoute: typeof ApiCrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/transfer': {
      id: '/api/crm/transfer'
      path: '/api/crm/transfer'
      fullPath: '/api/crm/transfer'
      preLoaderRoute: typeof ApiCrmTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/whatsapp-analysis': {
      id: '/api/cron/whatsapp-analysis'
      path: '/api/cron/whatsapp-analysis'
      fullPath: '/api/cron/whatsapp-analysis'
      preLoaderRoute: typeof ApiCronWhatsappAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/attendances': {
      id: '/api/gestao/attendances'
      path: '/api/gestao/attendances'
      fullPath: '/api/gestao/attendances'
      preLoaderRoute: typeof ApiGestaoAttendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/channels': {
      id: '/api/gestao/channels'
      path: '/api/gestao/channels'
      fullPath: '/api/gestao/channels'
      preLoaderRoute: typeof ApiGestaoChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/courses': {
      id: '/api/gestao/courses'
      path: '/api/gestao/courses'
      fullPath: '/api/gestao/courses'
      preLoaderRoute: typeof ApiGestaoCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/pipeline-columns': {
      id: '/api/gestao/pipeline-columns'
      path: '/api/gestao/pipeline-columns'
      fullPath: '/api/gestao/pipeline-columns'
      preLoaderRoute: typeof ApiGestaoPipelineColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ia-comercial/analises': {
      id: '/api/ia-comercial/analises'
      path: '/analises'
      fullPath: '/api/ia-comercial/analises'
      preLoaderRoute: typeof ApiIaComercialAnalisesRouteImport
      parentRoute: typeof ApiIaComercialRoute
    }
    '/api/ia-comercial/scripts': {
      id: '/api/ia-comercial/scripts'
      path: '/scripts'
      fullPath: '/api/ia-comercial/scripts'
      preLoaderRoute: typeof ApiIaComercialScriptsRouteImport
      parentRoute: typeof ApiIaComercialRoute
    }
    '/api/integrations/evolution': {
      id: '/api/integrations/evolution'
      path: '/api/integrations/evolution'
      fullPath: '/api/integrations/evolution'
      preLoaderRoute: typeof ApiIntegrationsEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/connect-url': {
      id: '/api/meta/connect-url'
      path: '/api/meta/connect-url'
      fullPath: '/api/meta/connect-url'
      preLoaderRoute: typeof ApiMetaConnectUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/oauth-complete': {
      id: '/api/meta/oauth-complete'
      path: '/api/meta/oauth-complete'
      fullPath: '/api/meta/oauth-complete'
      preLoaderRoute: typeof ApiMetaOauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/training/video': {
      id: '/api/training/video'
      path: '/video'
      fullPath: '/api/training/video'
      preLoaderRoute: typeof ApiTrainingVideoRouteImport
      parentRoute: typeof ApiTrainingRoute
    }
    '/api/webhooks/evolution': {
      id: '/api/webhooks/evolution'
      path: '/api/webhooks/evolution'
      fullPath: '/api/webhooks/evolution'
      preLoaderRoute: typeof ApiWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta-leads': {
      id: '/api/webhooks/meta-leads'
      path: '/api/webhooks/meta-leads'
      fullPath: '/api/webhooks/meta-leads'
      preLoaderRoute: typeof ApiWebhooksMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-supervision/access': {
      id: '/api/whatsapp-supervision/access'
      path: '/access'
      fullPath: '/api/whatsapp-supervision/access'
      preLoaderRoute: typeof ApiWhatsappSupervisionAccessRouteImport
      parentRoute: typeof ApiWhatsappSupervisionRoute
    }
    '/api/whatsapp-supervision/notifications': {
      id: '/api/whatsapp-supervision/notifications'
      path: '/notifications'
      fullPath: '/api/whatsapp-supervision/notifications'
      preLoaderRoute: typeof ApiWhatsappSupervisionNotificationsRouteImport
      parentRoute: typeof ApiWhatsappSupervisionRoute
    }
    '/financeiro/aluno/$studentId': {
      id: '/financeiro/aluno/$studentId'
      path: '/aluno/$studentId'
      fullPath: '/financeiro/aluno/$studentId'
      preLoaderRoute: typeof FinanceiroAlunoStudentIdRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/api/crm/leads/$id': {
      id: '/api/crm/leads/$id'
      path: '/$id'
      fullPath: '/api/crm/leads/$id'
      preLoaderRoute: typeof ApiCrmLeadsIdRouteImport
      parentRoute: typeof ApiCrmLeadsRoute
    }
    '/api/gestao/channels/$id': {
      id: '/api/gestao/channels/$id'
      path: '/$id'
      fullPath: '/api/gestao/channels/$id'
      preLoaderRoute: typeof ApiGestaoChannelsIdRouteImport
      parentRoute: typeof ApiGestaoChannelsRoute
    }
    '/api/gestao/courses/$id': {
      id: '/api/gestao/courses/$id'
      path: '/$id'
      fullPath: '/api/gestao/courses/$id'
      preLoaderRoute: typeof ApiGestaoCoursesIdRouteImport
      parentRoute: typeof ApiGestaoCoursesRoute
    }
    '/api/whatsapp-supervision/conversations/$id': {
      id: '/api/whatsapp-supervision/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/api/whatsapp-supervision/conversations/$id'
      preLoaderRoute: typeof ApiWhatsappSupervisionConversationsIdRouteImport
      parentRoute: typeof ApiWhatsappSupervisionRoute
    }
  }
}

interface CrmRouteChildren {
  CrmImportarRoute: typeof CrmImportarRoute
  CrmTransferenciaRoute: typeof CrmTransferenciaRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmImportarRoute: CrmImportarRoute,
  CrmTransferenciaRoute: CrmTransferenciaRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface FinanceiroRouteChildren {
  FinanceiroAlunoStudentIdRoute: typeof FinanceiroAlunoStudentIdRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroAlunoStudentIdRoute: FinanceiroAlunoStudentIdRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface ApiIaComercialRouteChildren {
  ApiIaComercialAnalisesRoute: typeof ApiIaComercialAnalisesRoute
  ApiIaComercialScriptsRoute: typeof ApiIaComercialScriptsRoute
}

const ApiIaComercialRouteChildren: ApiIaComercialRouteChildren = {
  ApiIaComercialAnalisesRoute: ApiIaComercialAnalisesRoute,
  ApiIaComercialScriptsRoute: ApiIaComercialScriptsRoute,
}

const ApiIaComercialRouteWithChildren = ApiIaComercialRoute._addFileChildren(
  ApiIaComercialRouteChildren,
)

interface ApiTrainingRouteChildren {
  ApiTrainingVideoRoute: typeof ApiTrainingVideoRoute
}

const ApiTrainingRouteChildren: ApiTrainingRouteChildren = {
  ApiTrainingVideoRoute: ApiTrainingVideoRoute,
}

const ApiTrainingRouteWithChildren = ApiTrainingRoute._addFileChildren(
  ApiTrainingRouteChildren,
)

interface ApiWhatsappSupervisionRouteChildren {
  ApiWhatsappSupervisionAccessRoute: typeof ApiWhatsappSupervisionAccessRoute
  ApiWhatsappSupervisionNotificationsRoute: typeof ApiWhatsappSupervisionNotificationsRoute
  ApiWhatsappSupervisionConversationsIdRoute: typeof ApiWhatsappSupervisionConversationsIdRoute
}

const ApiWhatsappSupervisionRouteChildren: ApiWhatsappSupervisionRouteChildren =
  {
    ApiWhatsappSupervisionAccessRoute: ApiWhatsappSupervisionAccessRoute,
    ApiWhatsappSupervisionNotificationsRoute:
      ApiWhatsappSupervisionNotificationsRoute,
    ApiWhatsappSupervisionConversationsIdRoute:
      ApiWhatsappSupervisionConversationsIdRoute,
  }

const ApiWhatsappSupervisionRouteWithChildren =
  ApiWhatsappSupervisionRoute._addFileChildren(
    ApiWhatsappSupervisionRouteChildren,
  )

interface ApiCrmLeadsRouteChildren {
  ApiCrmLeadsIdRoute: typeof ApiCrmLeadsIdRoute
}

const ApiCrmLeadsRouteChildren: ApiCrmLeadsRouteChildren = {
  ApiCrmLeadsIdRoute: ApiCrmLeadsIdRoute,
}

const ApiCrmLeadsRouteWithChildren = ApiCrmLeadsRoute._addFileChildren(
  ApiCrmLeadsRouteChildren,
)

interface ApiGestaoChannelsRouteChildren {
  ApiGestaoChannelsIdRoute: typeof ApiGestaoChannelsIdRoute
}

const ApiGestaoChannelsRouteChildren: ApiGestaoChannelsRouteChildren = {
  ApiGestaoChannelsIdRoute: ApiGestaoChannelsIdRoute,
}

const ApiGestaoChannelsRouteWithChildren =
  ApiGestaoChannelsRoute._addFileChildren(ApiGestaoChannelsRouteChildren)

interface ApiGestaoCoursesRouteChildren {
  ApiGestaoCoursesIdRoute: typeof ApiGestaoCoursesIdRoute
}

const ApiGestaoCoursesRouteChildren: ApiGestaoCoursesRouteChildren = {
  ApiGestaoCoursesIdRoute: ApiGestaoCoursesIdRoute,
}

const ApiGestaoCoursesRouteWithChildren =
  ApiGestaoCoursesRoute._addFileChildren(ApiGestaoCoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRoute,
  BiRoute: BiRoute,
  ConversasWhatsappRoute: ConversasWhatsappRoute,
  CrmRoute: CrmRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  IaComercialRoute: IaComercialRoute,
  LoginRoute: LoginRoute,
  MetaAdsRoute: MetaAdsRoute,
  PerfilRoute: PerfilRoute,
  TreinamentosRoute: TreinamentosRoute,
  UnidadesRoute: UnidadesRoute,
  UsuariosRoute: UsuariosRoute,
  ApiGrowthRoute: ApiGrowthRoute,
  ApiIaComercialRoute: ApiIaComercialRouteWithChildren,
  ApiMetaAdsRoute: ApiMetaAdsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiSystemFeedbackRoute: ApiSystemFeedbackRoute,
  ApiSystemSettingsRoute: ApiSystemSettingsRoute,
  ApiTrainingRoute: ApiTrainingRouteWithChildren,
  ApiWhatsappSupervisionRoute: ApiWhatsappSupervisionRouteWithChildren,
  GestaoCadastroRoute: GestaoCadastroRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ApiAdminUnitsRoute: ApiAdminUnitsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAtendimentosMidiaRoute: ApiAtendimentosMidiaRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiCrmImportRoute: ApiCrmImportRoute,
  ApiCrmLeadsRoute: ApiCrmLeadsRouteWithChildren,
  ApiCrmTasksRoute: ApiCrmTasksRoute,
  ApiCrmTransferRoute: ApiCrmTransferRoute,
  ApiCronWhatsappAnalysisRoute: ApiCronWhatsappAnalysisRoute,
  ApiGestaoAttendancesRoute: ApiGestaoAttendancesRoute,
  ApiGestaoChannelsRoute: ApiGestaoChannelsRouteWithChildren,
  ApiGestaoCoursesRoute: ApiGestaoCoursesRouteWithChildren,
  ApiGestaoPipelineColumnsRoute: ApiGestaoPipelineColumnsRoute,
  ApiHealthDbRoute: ApiHealthDbRoute,
  ApiIntegrationsEvolutionRoute: ApiIntegrationsEvolutionRoute,
  ApiMetaConnectUrlRoute: ApiMetaConnectUrlRoute,
  ApiMetaOauthCompleteRoute: ApiMetaOauthCompleteRoute,
  ApiWebhooksEvolutionRoute: ApiWebhooksEvolutionRoute,
  ApiWebhooksMetaLeadsRoute: ApiWebhooksMetaLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
