/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as GestaoCadastroRouteImport } from './routes/gestao.cadastro'
import { Route as CrmTransferenciaRouteImport } from './routes/crm.transferencia'
import { Route as ApiSystemSettingsRouteImport } from './routes/api/system-settings'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiGestaoCoursesRouteImport } from './routes/api/gestao/courses'
import { Route as ApiGestaoChannelsRouteImport } from './routes/api/gestao/channels'
import { Route as ApiGestaoAttendancesRouteImport } from './routes/api/gestao/attendances'
import { Route as ApiCrmTransferRouteImport } from './routes/api/crm/transfer'
import { Route as ApiCrmTasksRouteImport } from './routes/api/crm/tasks'
import { Route as ApiCrmLeadsRouteImport } from './routes/api/crm/leads'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminUnitsRouteImport } from './routes/api/admin/units'
import { Route as ApiGestaoCoursesIdRouteImport } from './routes/api/gestao/courses.$id'
import { Route as ApiGestaoChannelsIdRouteImport } from './routes/api/gestao/channels.$id'
import { Route as ApiCrmLeadsIdRouteImport } from './routes/api/crm/leads.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoCadastroRoute = GestaoCadastroRouteImport.update({
  id: '/gestao/cadastro',
  path: '/gestao/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmTransferenciaRoute = CrmTransferenciaRouteImport.update({
  id: '/transferencia',
  path: '/transferencia',
  getParentRoute: () => CrmRoute,
} as any)
const ApiSystemSettingsRoute = ApiSystemSettingsRouteImport.update({
  id: '/api/system-settings',
  path: '/api/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCoursesRoute = ApiGestaoCoursesRouteImport.update({
  id: '/api/gestao/courses',
  path: '/api/gestao/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoChannelsRoute = ApiGestaoChannelsRouteImport.update({
  id: '/api/gestao/channels',
  path: '/api/gestao/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoAttendancesRoute = ApiGestaoAttendancesRouteImport.update({
  id: '/api/gestao/attendances',
  path: '/api/gestao/attendances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTransferRoute = ApiCrmTransferRouteImport.update({
  id: '/api/crm/transfer',
  path: '/api/crm/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmTasksRoute = ApiCrmTasksRouteImport.update({
  id: '/api/crm/tasks',
  path: '/api/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmLeadsRoute = ApiCrmLeadsRouteImport.update({
  id: '/api/crm/leads',
  path: '/api/crm/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUnitsRoute = ApiAdminUnitsRouteImport.update({
  id: '/api/admin/units',
  path: '/api/admin/units',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGestaoCoursesIdRoute = ApiGestaoCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoCoursesRoute,
} as any)
const ApiGestaoChannelsIdRoute = ApiGestaoChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiGestaoChannelsRoute,
} as any)
const ApiCrmLeadsIdRoute = ApiCrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCrmLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/unidades': typeof UnidadesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/system-settings': typeof ApiSystemSettingsRoute
  '/crm/transferencia': typeof CrmTransferenciaRoute
  '/gestao/cadastro': typeof GestaoCadastroRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/admin/units': typeof ApiAdminUnitsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/crm/leads': typeof ApiCrmLeadsRouteWithChildren
  '/api/crm/tasks': typeof ApiCrmTasksRoute
  '/api/crm/transfer': typeof ApiCrmTransferRoute
  '/api/gestao/attendances': typeof ApiGestaoAttendancesRoute
  '/api/gestao/channels': typeof ApiGestaoChannelsRouteWithChildren
  '/api/gestao/courses': typeof ApiGestaoCoursesRouteWithChildren
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/crm/leads/$id': typeof ApiCrmLeadsIdRoute
  '/api/gestao/channels/$id': typeof ApiGestaoChannelsIdRoute
  '/api/gestao/courses/$id': typeof ApiGestaoCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/login'
    | '/perfil'
    | '/unidades'
    | '/usuarios'
    | '/api/profile'
    | '/api/system-settings'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/login'
    | '/perfil'
    | '/unidades'
    | '/usuarios'
    | '/api/profile'
    | '/api/system-settings'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/login'
    | '/perfil'
    | '/unidades'
    | '/usuarios'
    | '/api/profile'
    | '/api/system-settings'
    | '/crm/transferencia'
    | '/gestao/cadastro'
    | '/leads/$id'
    | '/leads/'
    | '/api/admin/units'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/crm/leads'
    | '/api/crm/tasks'
    | '/api/crm/transfer'
    | '/api/gestao/attendances'
    | '/api/gestao/channels'
    | '/api/gestao/courses'
    | '/api/health/db'
    | '/api/crm/leads/$id'
    | '/api/gestao/channels/$id'
    | '/api/gestao/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  UnidadesRoute: typeof UnidadesRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiSystemSettingsRoute: typeof ApiSystemSettingsRoute
  GestaoCadastroRoute: typeof GestaoCadastroRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ApiAdminUnitsRoute: typeof ApiAdminUnitsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiCrmLeadsRoute: typeof ApiCrmLeadsRouteWithChildren
  ApiCrmTasksRoute: typeof ApiCrmTasksRoute
  ApiCrmTransferRoute: typeof ApiCrmTransferRoute
  ApiGestaoAttendancesRoute: typeof ApiGestaoAttendancesRoute
  ApiGestaoChannelsRoute: typeof ApiGestaoChannelsRouteWithChildren
  ApiGestaoCoursesRoute: typeof ApiGestaoCoursesRouteWithChildren
  ApiHealthDbRoute: typeof ApiHealthDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/cadastro': {
      id: '/gestao/cadastro'
      path: '/gestao/cadastro'
      fullPath: '/gestao/cadastro'
      preLoaderRoute: typeof GestaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/transferencia': {
      id: '/crm/transferencia'
      path: '/transferencia'
      fullPath: '/crm/transferencia'
      preLoaderRoute: typeof CrmTransferenciaRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/system-settings': {
      id: '/api/system-settings'
      path: '/api/system-settings'
      fullPath: '/api/system-settings'
      preLoaderRoute: typeof ApiSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/courses': {
      id: '/api/gestao/courses'
      path: '/api/gestao/courses'
      fullPath: '/api/gestao/courses'
      preLoaderRoute: typeof ApiGestaoCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/channels': {
      id: '/api/gestao/channels'
      path: '/api/gestao/channels'
      fullPath: '/api/gestao/channels'
      preLoaderRoute: typeof ApiGestaoChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/attendances': {
      id: '/api/gestao/attendances'
      path: '/api/gestao/attendances'
      fullPath: '/api/gestao/attendances'
      preLoaderRoute: typeof ApiGestaoAttendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/transfer': {
      id: '/api/crm/transfer'
      path: '/api/crm/transfer'
      fullPath: '/api/crm/transfer'
      preLoaderRoute: typeof ApiCrmTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/tasks': {
      id: '/api/crm/tasks'
      path: '/api/crm/tasks'
      fullPath: '/api/crm/tasks'
      preLoaderRoute: typeof ApiCrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/leads': {
      id: '/api/crm/leads'
      path: '/api/crm/leads'
      fullPath: '/api/crm/leads'
      preLoaderRoute: typeof ApiCrmLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/units': {
      id: '/api/admin/units'
      path: '/api/admin/units'
      fullPath: '/api/admin/units'
      preLoaderRoute: typeof ApiAdminUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gestao/courses/$id': {
      id: '/api/gestao/courses/$id'
      path: '/$id'
      fullPath: '/api/gestao/courses/$id'
      preLoaderRoute: typeof ApiGestaoCoursesIdRouteImport
      parentRoute: typeof ApiGestaoCoursesRoute
    }
    '/api/gestao/channels/$id': {
      id: '/api/gestao/channels/$id'
      path: '/$id'
      fullPath: '/api/gestao/channels/$id'
      preLoaderRoute: typeof ApiGestaoChannelsIdRouteImport
      parentRoute: typeof ApiGestaoChannelsRoute
    }
    '/api/crm/leads/$id': {
      id: '/api/crm/leads/$id'
      path: '/$id'
      fullPath: '/api/crm/leads/$id'
      preLoaderRoute: typeof ApiCrmLeadsIdRouteImport
      parentRoute: typeof ApiCrmLeadsRoute
    }
  }
}

interface CrmRouteChildren {
  CrmTransferenciaRoute: typeof CrmTransferenciaRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmTransferenciaRoute: CrmTransferenciaRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface ApiCrmLeadsRouteChildren {
  ApiCrmLeadsIdRoute: typeof ApiCrmLeadsIdRoute
}

const ApiCrmLeadsRouteChildren: ApiCrmLeadsRouteChildren = {
  ApiCrmLeadsIdRoute: ApiCrmLeadsIdRoute,
}

const ApiCrmLeadsRouteWithChildren = ApiCrmLeadsRoute._addFileChildren(
  ApiCrmLeadsRouteChildren,
)

interface ApiGestaoChannelsRouteChildren {
  ApiGestaoChannelsIdRoute: typeof ApiGestaoChannelsIdRoute
}

const ApiGestaoChannelsRouteChildren: ApiGestaoChannelsRouteChildren = {
  ApiGestaoChannelsIdRoute: ApiGestaoChannelsIdRoute,
}

const ApiGestaoChannelsRouteWithChildren =
  ApiGestaoChannelsRoute._addFileChildren(ApiGestaoChannelsRouteChildren)

interface ApiGestaoCoursesRouteChildren {
  ApiGestaoCoursesIdRoute: typeof ApiGestaoCoursesIdRoute
}

const ApiGestaoCoursesRouteChildren: ApiGestaoCoursesRouteChildren = {
  ApiGestaoCoursesIdRoute: ApiGestaoCoursesIdRoute,
}

const ApiGestaoCoursesRouteWithChildren =
  ApiGestaoCoursesRoute._addFileChildren(ApiGestaoCoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  UnidadesRoute: UnidadesRoute,
  UsuariosRoute: UsuariosRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiSystemSettingsRoute: ApiSystemSettingsRoute,
  GestaoCadastroRoute: GestaoCadastroRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ApiAdminUnitsRoute: ApiAdminUnitsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiCrmLeadsRoute: ApiCrmLeadsRouteWithChildren,
  ApiCrmTasksRoute: ApiCrmTasksRoute,
  ApiCrmTransferRoute: ApiCrmTransferRoute,
  ApiGestaoAttendancesRoute: ApiGestaoAttendancesRoute,
  ApiGestaoChannelsRoute: ApiGestaoChannelsRouteWithChildren,
  ApiGestaoCoursesRoute: ApiGestaoCoursesRouteWithChildren,
  ApiHealthDbRoute: ApiHealthDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
